### ISSUE TITLE
Change order: COUNT_SRC at the end

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/make-novice#120]
Each time I teach this lesson I find the part where the `wordcount.py` script is changed to the `COUNT_SRC` variable, its execution to `COUNT_EXE` etc and the use of `config.mk` file hard to motivate. I.e. everything else in the lesson I use myself but not this. Also, the Makefile becomes much less readable.

Would it be OK to move this part to after the 'Functions' episode? A drawback would be that the 'Functions' episode then has to introduce variables and functions in one go. On the other hand, it can be done by first hardcoding the `.txt` files in the `TXT_FILES` and then replacing than with the `$(wildcard)` function.

If this suggestion is accepted, I can try to put in the PR but I am not sure when I would have the time for that.

**Comment by gcapes** [comment]
For anyone following, this issue refers to [episode 6](http://swcarpentry.github.io/make-novice/06-variables/) onwards.

I'm not sure I really understand this suggestion. Do you think that moving the variables episode to after the functions episode would improve flow of the lesson?

I particularly like `COUNT_SRC` and `COUNT_EXE`, because the variable names are well chosen to retain clarity, so I would disagree that this makes the Makefile less readable. Using `config.mk` to store variables is a great idea, but does have the trade-off of reduced readability of the Makefile.

**Comment by lexnederbragt** [comment]
My suggestion is to move the `COUNT_SRC` and `COUNT_EXE`parts of the variable lesson (and the corresponding variables for `zipf_test.py`) to after the functions lesson. 

May be it is personal style when setting up makefiles, but I would never put these scripts in a variable just in case I might change their name or switch from Python to R or something. But if it is 'best practice' then of course it should stay as it is.

**Comment by gcapes** [comment]
Thanks for clarifying your suggestion. I'm afraid I still don't understand the reasoning behind it though (last paragraph below).

There is of course a good amount of personal preference involved in setting up a Makefile, but I would say the motivation for using a variable to contain the script names is simply that the script names are repeated in the Makefile. Using a variable instead of repeating the script name makes the Makefile more robust by reducing typos, and as a bonus would simplify any future edits to the name of the script.

I would probably set up the `*_EXE` variables slightly differently, by including a variable to hold the language e.g.
```
LANGUAGE=python
COUNT_EXE=$(LANGUAGE) $(COUNT_SRC)
```
This would allow me to e.g. change to using python2 more easily. I might add this to the lesson at some point.

However, regardless of our preferences, how would moving the introduction of `*_SRC` and  `*_EXE` variables to after the functions episode improve the lesson? So far you've said that you wouldn't use these variables, which seems more of an argument to drop them rather than to reschedule their introduction.

**Comment by lexnederbragt** [comment]
I get the argumentation, thanks. Moving this use of variables to (more or less) the end is partly motivated by me thinking (maybe incorrectly) that this use is not as important as the other aspects of the lesson, partly by that it would make it easier to drop it when teaching :-)

**Comment by gcapes** [comment]
Ok, thanks for the discussion on this. I'll leave this a few days to give others the chance to chip in. My feeling though is that the argument to move or drop this usage isn't strong enough to warrant changing the lesson.

It's good practice to use a variable to store anything that is repeated, and separating the configuration from the rules is also a good practice to show.

**Comment by lexnederbragt** [comment]
Thanks. Closing now if that's OK
