### ISSUE TITLE
Recursive use of make

### ISSUE THREAD

**Issue by Deborah-Digges** [swcarpentry/make-novice#23]
I was thinking that a section on the recursive use of make(using make within a Makefile) would be a nice inclusion as it would teach students how to write separate Makefilse for various subsystems that compose a larger system. Perhaps another folder could be added which performs a different sort of analysis on the *.txt files along with a Makefile for this component, while the students would be writing the top level Makefile.
Would this be too advanced for the novice lesson?

**Comment by gvwilson** [comment]
I think recursive Make is too advanced for this lesson - what would 
probably be a better fit at this level is some discussion of how to 
handle platform dependencies (i.e., how to write a Makefile that works 
on Windows as well as Unix, or even one that handles the differences 
between different flavors of Unix).

**Comment by Deborah-Digges** [comment]
I think that is an excellent idea. I'd be glad to get started working on this. 
Are there any specific points you would like me to highlight in the lesson?

**Comment by gvwilson** [comment]
Part of the old lesson on macros 
(http://software-carpentry.org/v4/make/macros.html) showed how to put 
configuration variables in a separate file that could then be included 
in the main Makefile.  Showing people how to do that to manage 
differences in tool names and/or tool parameters would probably be a 
good addition - maybe do a PR with a new topic file containing a dozen 
bullet points outlining what you'd cover, so that people can give 
feedback before you write a whole lesson?

**Comment by mikej888** [comment]
06-variables.md also has a very simple example of variables in a separate fiile.

**Comment by Deborah-Digges** [comment]
@gvwilson @mikej888 Thank you for the feedback. I will send in a PR soon. :-)

**Comment by bsmith89** [comment]
:-1:  See [Recursive Make Considered Harmful](http://aegis.sourceforge.net/auug97.pdf).

**Comment by mikej888** [comment]
Closing this issue as it's been static for 8 months. It can be re-opened if necessary.
