### ISSUE TITLE
Key Point introduction

### ISSUE THREAD

**Issue by willibry** [swcarpentry/make-novice#66]
I find the key point in the introduction a bit unclear. 

> Make allows us to specify what depends on what and how to update things that are out of date. 

Does Make allow us to specify _how_ to update things?

It might be better to drop the 'how: 

> Make allows us to specify what depends on what and to update things that are out of date. 

Another suggestion:

> Make allows you to specify what depends on what. If you make a change, Make will only update things that need to be updated.

What do you think?

**Comment by gcapes** [comment]
Make does allow us to specify the *how* - we specify what commands need to be run in order to make/update any given object.
That Make only updates those objects which need to be updated, is covered in the next episode where it talks about incremental builds.

I don't think any of the suggested changes are required. Please let me know if you disagree and we can discuss further. 
Thanks

**Comment by gcapes** [comment]
Closed due to lack of further discussion
